spring:
  application:
    name: Taxi-User
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taxi
    username: postgres
    password: postgres
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  queue:
    notify-driver: notifier_queue
    reporter: reporter_queue
  routing:
    notify-driver: notifier_key
    reporter: reporter_key

logging:
  level:
    org:
      springframework:
        security: trace

server:
  port: 9090
